### PR TITLE
Several expansions

### PR DESCRIPTION
**Pull request by MathyFurret**
Can now:
*Move pages
*List all redirects
*Mark edits as minor (as default)

When reading pages, it limits the query to 1 revision which may make it faster.

Also changed r.json to r.json() like we agreed it should be.

### CODE REVIEW

**Comment by tjvr** [comment]
Looks good, but please could you clean up the formatting? http://www.python.org/dev/peps/pep-0008/ Thanks!

**Comment by MathyFurret** [comment]
I think I got it. If my choice of line spacing isn't how you want it, you can change it yourself.

**Comment by MathyFurret** [comment]
Ya.

**Comment by MathyFurret** [comment]
Okay, moving is apparently broken because the "from" parameter, also being a key word, gives a SyntaxError. If you can work around that, it'd be lovely.

**Comment by tjvr** [comment]
> "from" parameter, also being a key word

The convention for function arguments is to use `from_`.

**Comment by MathyFurret** [comment]
Yes, but the parameter in the request is "from". See https://www.mediawiki.org/wiki/API:Move#Parameters .

It can probably be worked around using `fromid` instead. Gimme a bit.

**Comment by MathyFurret** [comment]
Done.

**Pull request closed without merging**
